version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: bundle install && rake build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
